### PR TITLE
Submission for Dufuna-uxDesign Task

### PR DESCRIPTION
**Pull request by kolawolejohn**

### CODE REVIEW

**Review by goke-epapa — CHANGES_REQUESTED** [review]
Hi @kolawolejohn,

Your submission does not follow the submission guidelines in the README file, please pay close attention to it especially the part highlighted below:
```
In your fork, in the submissions directory, create a new folder whose name is YOUR FULL NAME.

In the folder named after you, create another folder named the topic for which you want to make a submission Example: uxDesign

In this directory, create a new file with the solution of each task. Example: uxDesign.txt
```
Once you make the changes, please push your changes so this Pull Request (PR) would be updated

**Comment by kolawolejohn** [comment]
> Hi @kolawolejohn,
> 
> Your submission does not follow the submission guidelines in the README file, please pay close attention to it especially the part highlighted below:
> 
> ```
> In your fork, in the submissions directory, create a new folder whose name is YOUR FULL NAME.
> 
> In the folder named after you, create another folder named the topic for which you want to make a submission Example: uxDesign
> 
> In this directory, create a new file with the solution of each task. Example: uxDesign.txt
> ```
> 
> Once you make the changes, please push your changes so this Pull Request (PR) would be updated

I have tried everything I could, but, I don't see the files I added when I reload my github.

**Comment by goke-epapa** [comment]
@kolawolejohn can you share the list of steps/commands you are using?

**Comment by kolawolejohn** [comment]
I have overhaul the whole step.

I think i have it now, wireframe is giving me headache.

git clone url
cd to the clone folder
cd submissions/
mkdir kolawoleOgunfowokan
cd kolawoleOgunfowokan
mkdir uxDesign
cd uxDesign
git branch myTask
git checkout myTask
paste the files
git add .
git status
git commit -m "message"
git push

**Comment by goke-epapa** [comment]
Ok, Please close this PR since you have another [PR](https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp19/pull/7) open

**Pull request closed without merging**
