### PR TITLE
my database task

### PR DESCRIPTION
**Pull request by Eudoh940**
my database task

### CODE REVIEW

**Comment by rasheedsulayman** [comment]
Hello @Eudoh940, Please check your permissions and make the document public-readable.  I wasn't able to access the document in your PR: https://docs.google.com/document/d/1gsY608JzU1I6pCKo8MAW7dOpgS8i6ekWH-owS-qwD-A/edit

**Comment by rasheedsulayman** [comment]
Also, Please note that you only need to add the link to your google-docs document to  the file "my database task.txt". Every other stuff should be in the google-docs document. Don't forget to check  the [sample submission](https://docs.google.com/document/d/1iKG_UjMeq8Q_IINZABm-B9SHtl6RQGyUfAD811hPNMg/edit) for the format. 

i.e "my database task.txt" should only contain this line: 
`https://docs.google.com/document/d/1gsY608JzU1I6pCKo8MAW7dOpgS8i6ekWH-owS-qwD-A/edit`

**Comment by Eudoh940** [comment]
done

**Comment by Eudoh940** [comment]
I have done the corrections

**Comment by rasheedsulayman** [comment]
Hello @Eudoh940 . Please add the questions to your document. It's not so easy to see the questions you're answering.  
Screen Shot 2020-01-01 at 8 17 53 PM

As you can see from the attached image, each answers will have the original question, sql statement, then the screenshot.

**Comment by Eudoh940** [comment]
the questions have been added. Thanks

**Comment by Eudoh940** [comment]
i have modified my solution to something better

**Review by kenny-wealth — APPROVED** [review]

**Review by rasheedsulayman — APPROVED** [review]
Well done @Eudoh940. It is much better now.

**Comment by Eudoh940** [comment]
Ok..   thanks... Merging required.. 😁

**Pull request merged**
