### PR TITLE
Html task

### PR DESCRIPTION
**Pull request by bnokoro**

### CODE REVIEW

**Comment by adaugochi** [comment]
Have you submitted your wireframe? Also, your PR description says HTML task meanwhile I am also seeing a Docx file for your user story. Learn to make your commit message and PR more descriptive

**Comment by bnokoro** [comment]
I submitted my wire frame as well as user story too last week but while i was working on my HTML assignment, i realised that i missed out on some points so i made the additions. So the first comment that says "changes made to userstories" was actually referring to the updates i added.
Then HTML task is a new branch i created under the master branch which says “this is my HTML assignment "

**Comment by adaugochi** [comment]
ok

**Review by adaugochi — APPROVED** [review]

**Review by goke-epapa — APPROVED** [review]
Well done!

**Pull request merged**
