### PR TITLE
uxDesign Submission

### PR DESCRIPTION
**Pull request by kolawolejohn**
- All my files have been added
- Process Flow
- User Story
- Mockup

### CODE REVIEW

**Comment by otaruMendez** [comment]
Hi @kolawolejohn, you

**Comment by otaruMendez** [comment]
Hi @kolawolejohn, you have two PR's opened on the same task. We have to close one to avoid confusion. which do you want closed?

**Comment by kolawolejohn** [comment]
I will like to close the one that I had a read me file on my folder.

Thanks

**Comment by otaruMendez** [comment]
Okay, you also modified (deleted) the READMe in this one too though. I will close the other one but please revert the changes on the ReadMe file here too. You can reach out to any of the mentors on the #versioncontrol channel for help.

**Comment by kolawolejohn** [comment]
I really don't know what to do again. I was told to delete the readme file
in my folder that it shouldn't appear. So do I put it back?

**Comment by otaruMendez** [comment]
Okay, let us work through this together on slack.

**Comment by kolawolejohn** [comment]
If I can delete this whole repo, and start afresh, I will make everything
clean and right, if not, I really don't know what to do. Because, when the
Readme was there I was told to remove it, now I have to put it back. I
really shouldn't be having issue on this git thing. But I am ready to
listen, so question is what should I really do. Maybe if I understand that,
I can fix it.

**Comment by kolawolejohn** [comment]
I had to do a fresh one.

**Pull request closed without merging**
