### PR TITLE
HTML task

### PR DESCRIPTION
**Pull request by Epresh**

### CODE REVIEW

**Comment by Epresh** [comment]
I had to finish the form before the pull request.

**Comment by kenny-wealth** [comment]
Nice attempt @Epresh. Two things:
1. The two files in this PR are very identical. Is that what you intended to do?
2. Indentation seems off on the HTML files. You can check out [https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html](https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html) for some tips

**Comment by Epresh** [comment]
i added some new codes and made the corrections i accordingly.

**Comment by Epresh** [comment]
> Nice attempt @Epresh. Two things:
> 
> 1. The two files in this PR are very identical. Is that what you intended to do?
> 2. Indentation seems off on the HTML files. You can check out https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html for some tips

i have made the corrections to the indentation and also imoroved the form to the best of my knowledge.

**Pull request closed without merging**
