### PR TITLE
Html file V1

### PR DESCRIPTION
**Pull request by abolayo**
i added dufuna.html file  to html.css folder for the first html task

### CODE REVIEW

**Comment by JohnItoo** [comment]
Hello @abolayo . To allow your changes to be tracked easily, and for consistency, kindly rename your `html-css` directory to `HTML`

**Comment by abolayo** [comment]
i rename  the  folder  from html-css to html

**Comment by goke-epapa** [comment]
@abolayo you are almost there, please remove the `html-css` folder from the repository

You can do this by deleting the folder
staging your changes by running `git add html-css` from the `medinatapanpa` directory
commit your changes `git commit -m "descriptive commit message"`
and pushing your changes `git push origin dufunaDesign`

**Comment by abolayo** [comment]
trying to solve the problem.., but i eventually messed the whole thing up. the submissions folder on my desktop is empty.. am confuse.

**Comment by abolayo** [comment]
i have deleted the html-css folder

**Review by goke-epapa — APPROVED** [review]

**Review by JohnItoo — APPROVED** [review]

**Pull request merged**
