### PR TITLE
create html v.1

### PR DESCRIPTION
**Pull request by abolayo**
I added dufuna.html that contain html Task

### CODE REVIEW

**Comment by otaruMendez** [comment]
@abolayo can you please also add the wireframes and process requirement document?

**Comment by abolayo** [comment]
i thought the uxDesign task is to be in a uxDesign folder and html in a another folder named html-css. didnt know am to add them in the same folder.
i did submissions/medinat/uxDesign for the first task and submissions/medinat/html-css for the second task.......

**Review by liomotolani — DISMISSED** [review]

**Comment by adaugochi** [comment]
The Html file you are submitting is empty...why?

**Review by liomotolani — COMMENTED** [review]
@abolayo please check the html file you added, thank you

**Pull request closed without merging**
