### PR TITLE
Versioncontrol uxDesign and HTML

### PR DESCRIPTION
**Pull request by Olumide77**
I added processflow and wireframe files for uxDesign version control

### CODE REVIEW

**Comment by otaruMendez** [comment]
Everything on your PR looks good except the .gitignore file. Please revert the changes in the .gitignore file, it shouldn't show up at all in your PR. Welldone so far @Olumide77

**Comment by Olumide77** [comment]
Thank you very much @OtaruMendez. Do I have t o just delete it and notify you that I have done that or is there any other thing I am expected to do after deleting the file?

**Comment by otaruMendez** [comment]
Not really, you have to revert your changes on that file (.gitignore). You can hit me up on slack for follow up.

**Comment by rasheedsulayman** [comment]
@otaruMendez  I think the [.gitignore file](https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp19/blob/master/submissions/.gitignore) has already been deleted in one the the recent commits to `master`. It is probably showing in the diff because his `fork` is not in sync the the main repo.

@Olumide77 you can try to sync/update you fork by following the steps listed [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

**Review by rasheedsulayman — APPROVED** [review]

**Review by otaruMendez — APPROVED** [review]

**Pull request merged**
