### PR TITLE
my project

### PR DESCRIPTION
**Pull request by Eudoh940**

### CODE REVIEW

**Comment by otaruMendez** [comment]
Nice work @Eudoh940, can you change the file name from ```Copy of Emmanuel udoh process flow (2).pdf ``` to something more expressive. I think ```Emmanuel udoh process flow.pdf``` is just fine.

**Comment by Eudoh940** [comment]
Alright sir...thanks. it will be done

**Comment by Eudoh940** [comment]
i have made the changes to my process flow file name

**Comment by Eudoh940** [comment]
#12

**Review by beccadaniel — APPROVED** [review]

**Review by adaugochi — DISMISSED** [review]

**Comment by adaugochi** [comment]
the directory should be `submissions folder->your name folder->ux design folder->then the file to submit`. Please correct that

**Pull request closed without merging**
