### PR TITLE
This is my Database task

### PR DESCRIPTION
**Pull request by olumid300**
### Task: MySQL Database Task<task name here>

I added my database task txt file in a database folder.<clear and concise explanation>
I created a database 
I added 3 tables to the database
I inserted records into the database table
I updated the database records
I performed an inner join with two tables <clear and concise explanation>

### CODE REVIEW

**Comment by olumid300** [comment]
@r4sh33d @kenny-wealth @otaruMendez please kindly review my PR. thanks

**Review by adaugochi — APPROVED** [review]

**Comment by kenny-wealth** [comment]
This seems more than the database task. Please update the description to reflect what you did

**Comment by olumid300** [comment]
> This seems more than the database task. Please update the description to reflect what you did

@kenny-wealth i have updated the description. thanks

**Comment by kenny-wealth** [comment]
> > This seems more than the database task. Please update the description to reflect what you did
> 
> @kenny-wealth i have updated the description. thanks
There are some other files in this PR apart from the `database.txt` file. Can you remove them if they are not part of this task? Have you done the Javascript task before now?

**Comment by olumid300** [comment]
@kenny-wealth My JavaScript task has been merged. oh! i pushed my java script task from another branch and added the file in this branch. Do I need to delete the Javascript task from this branch? or how do i resolve it

**Comment by tegaphilip** [comment]
@olumid300 if your javascript task from another branch has already been merged, you need to update this branch to contain the latest code that has already been merged.

See https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a

if you need further help, ping me on slack.

**Pull request closed without merging**
