### PR TITLE
uxDesign

### PR DESCRIPTION
**Pull request by Lumi007**
Hello, Kindly review my week 1 assignments on uxDesign

### CODE REVIEW

**Review by adaugochi — DISMISSED** [review]
Well done @Lumi007

**Review by adaugochi — DISMISSED** [review]

**Review by Lumi007 — COMMENTED** [review]
I added social sign up to the sign-up page

**Comment by otaruMendez** [comment]
Your PR looks really good @Lumi007, Great job!

**Review by otaruMendez — APPROVED** [review]

**Review by adaugochi — APPROVED** [review]

**Comment by Lumi007** [comment]
Thank You @adaugochi and @otaruMendez

**Pull request merged**
