### PR TITLE
My uxDesign Task

### PR DESCRIPTION
**Pull request by Heedharyhart**
I have submitted my uxDesign task on Dufuna-CampCode19

### CODE REVIEW

**Comment by otaruMendez** [comment]
I can't seem to see any file here. Was that on purpose? @Heedharyhart

**Comment by Heedharyhart** [comment]
I submitted the file. I dont know why you are not receiving it

**Comment by otaruMendez** [comment]
Oh really @Heedharyhart, sorry about that. You can talk to any of the mentors on slack to help you out.

**Comment by yemexx1** [comment]
@Heedharyhart the files are still empty, did you make any progress?

**Pull request closed without merging**
