### PR TITLE
Database Task

### PR DESCRIPTION
**Pull request by kolawolejohn**
What I have done
- I separated the database from THE HTML, CSS and JS folder
- Placed the database folder  in my named folder.
- I added the database.txt file to the database folder
- Used a better way to delete rows from a table that has a foreign key in another table by adding "ON CASCADE DELETE"
- Finished and pushed to a new branch

### CODE REVIEW

**Comment by kenny-wealth** [comment]
Please submit the database task in a separate PR.

**Comment by kolawolejohn** [comment]
It is actually a separate PR, the JS PR is #121, this is #124. Please, how else can it separate? I have tried to push again on a different branch same.

**Comment by kenny-wealth** [comment]
> It is actually a separate PR, the JS PR is #121, this is #124. Please, how else can it separate? I have tried to push again on a different branch same.

That is probably because you checked out the database branch from the js branch. Can you try checking out directly from master or rebase this branch.

`git rebase --onto master <js-branch-name> <database-task-branch>`

See more on git rebase here https://git-scm.com/docs/git-rebase

**Comment by kolawolejohn** [comment]
I have done that, and created a new PR #126, clean now I think. So do I close #124 @kenny-wealth ?

**Comment by kenny-wealth** [comment]
> I have done that, and created a new PR #126, clean now I think. So do I close #124 @kenny-wealth ?

Yes, please

**Pull request closed without merging**
