### PR TITLE
database task

### PR DESCRIPTION
**Pull request by abolayo**
I completed my database task

### CODE REVIEW

**Review by rasheedsulayman — COMMENTED** [review]
Hello @abolayo , Please check your permissions and make the document accessible. I wasn't able to access the document in your PR:
https://docs.google.com/document/d/1JvRGwFd8lXBk5Ql8oxi22uXYjsw_AA76IlaiPC3pLyw/edit

**Comment by abolayo** [comment]
> Hello @abolayo , Please check your permissions and make the document accessible. I wasn't able to access the document in your PR:
> https://docs.google.com/document/d/1JvRGwFd8lXBk5Ql8oxi22uXYjsw_AA76IlaiPC3pLyw/edit

https://docs.google.com/document/d/1JvRGwFd8lXBk5Ql8oxi22uXYjsw_AA76IlaiPC3pLyw/edit?usp=sharing

**Review by tegaphilip — APPROVED** [review]
Conversations should take place on the google doc. Approving.

**Review by rasheedsulayman — APPROVED** [review]
Nice to see that you tried out those queries.

**Pull request merged**
