### PR TITLE
Idayat

### PR DESCRIPTION
**Pull request by Heedharyhart**
my HTML Task

### CODE REVIEW

**Comment by otaruMendez** [comment]
Good start @Heedharyhart, please make some adjustments on this PR: 
1. Please remove the uxDesign file in the base directory.
2. It will be nice to rename your HTML TASK folder to just HTML for consistency with the naming convention.
2. Please make your PR title more descriptive. I suggest this: ```Add uxDesign and HTML tasks```. If something more descriptive comes to mind than this, please use it.

**Comment by otaruMendez** [comment]
Good start @Heedharyhart, please make some adjustments on this PR: 
1. Please remove the uxDesign file in the base directory.
2. It will be nice to rename your HTML TASK folder to just HTML for consistency with the naming convention.
3. Please make your PR title more descriptive. I suggest this: ```Add uxDesign and HTML tasks```. If something more descriptive comes to mind than this, please use it.

**Comment by Heedharyhart** [comment]
Good afternoon sir,
I'm  resubmitting my tasks from the first task to Html by creating another
branch for the two
Thanks sir

**Comment by tegaphilip** [comment]
@Heedharyhart if you want to create another pull request that does the same as an old one, you should delete the old one. I see you have many open pull requests. Please close the old or stale ones. Thank you very much.

**Pull request closed without merging**
