### PR TITLE
MySQL_Task

### PR DESCRIPTION
**Pull request by Epresh**
MySQL Task

### CODE REVIEW

**Comment by kenny-wealth** [comment]
> Thus is the CSS submission.

Is there a CSS submission in here?

**Comment by kenny-wealth** [comment]
> MySQL Task

The task requires you to do the task on  Google Docs and submit the link to the document in a PR. Please visit the #databases channel to get more information

**Comment by Epresh** [comment]
Good morning Ma.
i have made the corrections as instructed and this is the PR to that effect

https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp19/compare/master...Epresh:precious_erhabor_MySQL?expand=1

**Review by adaugochi — DISMISSED** [review]

**Comment by rasheedsulayman** [comment]
Hello @Epresh The instruction in the slides is to use a single document. And follow this [format](https://docs.google.com/document/d/1iKG_UjMeq8Q_IINZABm-B9SHtl6RQGyUfAD811hPNMg/edit). It's not so convenient to review those individual documents, without question labels.

**Review by rasheedsulayman — DISMISSED** [review]

**Comment by rasheedsulayman** [comment]
Hello @Epresh. Please add the questions to your document. It's not so easy to see the questions you're answering.  
Screen Shot 2020-01-01 at 8 17 53 PM

As you can see from the attached image, each answers will have the original question, sql statement, then the screenshot.

**Comment by Epresh** [comment]
Okay sir

**Review by rasheedsulayman — APPROVED** [review]
I just checked again. Well done @Epresh

**Comment by Epresh** [comment]
But I still need one more approval for the submission to be merged

**Review by netwox — APPROVED** [review]
Well done @Epresh

**Pull request merged**
