### PR TITLE
Olaide

### PR DESCRIPTION
**Pull request by Heedharyhart**
My latest and complete solution of the uxDesign task 
All files are added

### CODE REVIEW

**Review by tegaphilip — DISMISSED** [review]
Good work

**Comment by goke-epapa** [comment]
Well done @Heedharyhart; you are almost there

Please remove the `uxDesign` file from the repository and push your changes

**Comment by Heedharyhart** [comment]
I have updated my html task without uxDesign design as commented on earlier

**Review by goke-epapa — COMMENTED** [review]
Looks like you deleted the `README.md` and the `.gitignore` file.
Please re-add them and push your changes

**Pull request closed without merging**
