### PR TITLE
Add style guide doc

### PR DESCRIPTION
**Pull request by kenny-wealth**
This doc is intended to be a quick reference for code formatting

### CODE REVIEW

**Review by yemexx1 — COMMENTED** [review]
Super cool! What do you think about adding a table of content above so it's easy to navigate to styleguide for language of interest

**Comment by kenny-wealth** [comment]
> Super cool! What do you think about adding a table of content above so it's easy to navigate to styleguide for language of interest

Good idea! Updated

**Review by yemexx1 — APPROVED** [review]
❤️

**Comment by otaruMendez** [comment]
Super great work! @kenny-wealth. Welldone.

**Review by otaruMendez — APPROVED** [review]

**Pull request merged**
