### PR TITLE
HTML Task

### PR DESCRIPTION
**Pull request by kolawolejohn**
I added my HTML files, which are:
- my Image folder
- index.html

### CODE REVIEW

**Comment by ToluAkin** [comment]
Well done.

**Review by ToluAkin — APPROVED** [review]

**Review by otaruMendez — APPROVED** [review]

**Review by goke-epapa — COMMENTED** [review]
All good for your HTML tasks well done 👏

A few comments
1. Your branch is named DesignTask even though this is an HTML task, please change if you can or note it for subsequent tasks

2. I noticed you have files for the UX Design task in the PR as well, any reason why?

**Comment by kolawolejohn** [comment]
> All good for your HTML tasks well done 👏
> 
> A few comments
> 
> 1. Your branch is named DesignTask even though this is an HTML task, please change if you can or note it for subsequent tasks
> 2. I noticed you have files for the UX Design task in the PR as well, any reason why?

**On comment one**, _I have changed the name of my branch to a befitting one that describes the task "HtmlTask, am I to delete the old one and do a new PR?_
**on comment two**, _we were told to create the HTML folder in the directory that contained our uxDesign folder, that is why the uxDesign folder appeared in the PR._

**Comment by goke-epapa** [comment]
Thanks for attending to the comments and for the clarifications.

No need to create a new PR, I'll approve

**Review by goke-epapa — APPROVED** [review]

**Review by adaugochi — APPROVED** [review]

**Pull request merged**
